service:
  name: serverless-cloudwatch-log-example

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  memorySize: 128

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  foo:
    handler: handler.foo
    events:
      - http:
          method: get
          path: foo
  bar:
    handler: handler.bar
    events:
      - http:
          method: get
          path: bar
  subscribe:
    handler: handler.subscribe
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/${self:service.name}-${self:provider.stage}-foo'
          filter: 'MYLOG'
      - cloudwatchLog:
          logGroup: '/aws/lambda/${self:service.name}-${self:provider.stage}-bar'
          filter: 'MYLOG'

